### ISSUE TITLE
서버 구축

### ISSUE THREAD

**Issue by BEDongryeol** [BC-MOA/MOA-BE#4]
## 이슈 내용
Docker, AWS를 통한 서버 구축

## 상세 내용
- Backend, Frontend, DB 컨테이너 빌드 후 docker-compose.yml 파일로 생성
- AWS EC2에서 image pull & run

## Todo
- [x] DB 포트 포워딩
- [x] docker-compose 파일 생성 
- [x] AWS EC2 생성
- [x] AWS EC2에서 구동
